"""initial migrate

Revision ID: 389a7ed04ec5
Revises: 
Create Date: 2022-02-13 13:12:58.694182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389a7ed04ec5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('image', sa.Text(), nullable=True))
    op.drop_column('users', 'profile_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('blogs', 'image')
    # ### end Alembic commands ###
