"""Initial migrate

Revision ID: 9a4b32066245
Revises: c53ae4977adc
Create Date: 2022-02-13 10:35:20.286723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4b32066245'
down_revision = 'c53ae4977adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img', sa.Text(), nullable=False))
    op.alter_column('users', 'full_names',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'full_names',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'profile_img')
    # ### end Alembic commands ###
